apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: "4Gi"
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data1
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
spec:
  capacity:
    storage: "4Gi"
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data2
    type: DirectoryOrCreate
